-- 코드를 입력하세요
SELECT LEFT(ONS.SALES_DATE,10) as SALES_DATE, ONS.PRODUCT_ID, ONS.USER_ID, ONS.SALES_AMOUNT
FROM ONLINE_SALE ONS
WHERE SUBSTR(SALES_DATE,7,1) = "3"
UNION ALL
SELECT LEFT(OFS.SALES_DATE,10) as SALES_DATE, OFS.PRODUCT_ID, NULL as USER_ID, OFS.SALES_AMOUNT
FROM OFFLINE_SALE OFS
WHERE SUBSTR(SALES_DATE,7,1) = "3"
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID